name: Get Folder Name

on:
  push:
    branches:
      - main

jobs:
  get-folder-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get folder name
      id: get-folder-name
      run: |
        # Get the branch name
        branch_name=$(git rev-parse --abbrev-ref HEAD)
        
        git ls-tree -d --name-only $branch_name

        # Extract the folder name from the branch name (assuming the branch name is in the format 'folder/branch')
        folder_name=${branch_name%%/*}

        echo "Folder name: $folder_name"
